# Generated by Django 6.0.6 on 2026-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='department',
            field=models.CharField(default='CGI Artist', max_length=100),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='purpose',
            field=models.TextField(default='CGI Artist'),
            preserve_default=False,
        ),
    ]
